Module9 task1
htmlacademy-javascript/414933-kekstagram-23 pull request #10
Opened 2021-07-11 21:55 UTC by EvgenKalinin

2021-07-11 22:37 UTC, AlexMasterov requested changes

2021-07-11 22:37 UTC, AlexMasterov commented on js/form.js
> +    effectsList.addEventListener('change', onEffectChange);
`effectsList` + `change` !== on`Effect`Change`

[`Д 4`](https://up.htmlacademy.ru/javascript/23/criteries#d4)
> Из названия обработчика события и функции-колбэка следует, что это обработчик

> Название обработчика строится следующим образом:

> `on` + **`(на каком элементе)`** + `что случилось`

2021-07-11 22:37 UTC, AlexMasterov commented on js/scale.js
> +  controlSmaller.addEventListener('click', onSmallerButtonClick);
`controlBigger` + `click` !== on`BiggerButton`Click
`controlSmaller` + `click` !== on`SmallerButton`Click

Д4

2021-07-11 22:37 UTC, AlexMasterov commented on js/effects.js
> +  const currentEffect = effects.find((effect) => effect.name === evt.target.value);
<details>
<summary>effects.js</summary>

https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/f12a91ea389a4e512a9f6b750dcf32cc82995bfe/js/effects.js#L7-L51
https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/f12a91ea389a4e512a9f6b750dcf32cc82995bfe/js/effects.js#L91
</details>

Можно обойтись без цикла, если вместо массива лучше использовать объект в роли _словаря_: `O(N`) -> `O(1)`.

2021-07-11 22:37 UTC, AlexMasterov commented on js/effects.js
> +  imgPreview.classList.add(`effects__preview--${effect.style}`);
imgPreview.`className = ''`

Таким образом с элемента удаляются _все_ CSS-классы.

2021-07-11 22:37 UTC, AlexMasterov commented on index.html
<details>
<summary>gallery.js</summary>

https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/f12a91ea389a4e512a9f6b750dcf32cc82995bfe/js/gallery.js#L26
</details>

Сейчас если закрыть большое фото нажатием на кнопку, то на `document` останется обработчик `keydown`.

Б26

Попробуй с помощью коллбэка узнать о закрытии фотографии и в нем удалить обработчик.

2021-07-11 22:37 UTC, AlexMasterov commented on js/effects.js
> +
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/125211623-60239c00-e2b0-11eb-8569-c0858259ba8f.png)

</details>

См. ТЗ:
> При выборе эффекта «Оригинал» слайдер скрывается

Нужно полностью скрыть слайдер.

2021-07-11 22:37 UTC, AlexMasterov commented on js/effects.js
> +  effectSlider.noUiSlider.on('update', (values, handle) => {
При переключение эффектов на баре и перемещении ползунка слайдера накапливаются обработчики на `update`. Работа эффектов и слайдера ломается.

Б26

Нужно разобраться и исправить.

2021-07-11 22:37 UTC, AlexMasterov commented on js/scale.js
> +
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/125211743-28692400-e2b1-11eb-834d-e67c8530cd58.png)
</details>

См. 3.6, 3.3:
> масштаб возвращается к 100%

Нужно доработать.

2021-07-13 19:04 UTC, EvgenKalinin commented on js/effects.js
> +  effectSlider.noUiSlider.on('update', (values, handle) => {
Эту проблему не могу поймать.

2021-07-13 22:25 UTC, AlexMasterov commented on js/effects.js
> +  effectSlider.noUiSlider.on('update', (values, handle) => {
> Эту проблему не могу поймать.

<details>
<summary>onEffectListChange</summary>

https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/47e48429da28b8e94162cfcacf9f6ca6eadaf088/js/effects.js#L93-L99
https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/47e48429da28b8e94162cfcacf9f6ca6eadaf088/js/form.js#L54
</details>

Посмотри внимательно: при смене эффекта в обработчике `onEffectListChange` вызывается функция `setEffect`:

<details>
<summary>setEffect</summary>

https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/47e48429da28b8e94162cfcacf9f6ca6eadaf088/js/effects.js#L65-L83
</details>

В этой функции для `noUiSlider` на событие `update` в качестве обработчика используется каждый раз новая _анон. функция_. Таким образом на каждый вызов `setEffect` добавляется новый обработчик. 

Накопление обработчиков приводит к замедлению интерфейса выбора эффектов и увеличивает потребление памяти (без возможности очистки сборщиком мусора), что в итоге приводит к падению всей страницы.

2021-07-15 19:20 UTC, EvgenKalinin commented on js/effects.js
> +  effectSlider.noUiSlider.on('update', (values, handle) => {
Я извиняюсь. Я не понимаю что нужно сделать.(

2021-07-17 11:00 UTC, AlexMasterov reviewed
Сейчас важно постараться доделать задания по обяз. части ТЗ.

Пожалуйста, мелкие замечания в остатке исправь при выполнении след. задания.

> Куратор: 21.07 — дедлайн на получение допуска у своего наставника

2021-07-17 11:01 UTC, merged