Module11 task1
htmlacademy-javascript/414933-kekstagram-23 pull request #11
Opened 2021-07-18 16:18 UTC by EvgenKalinin

2021-07-19 00:03 UTC, AlexMasterov requested changes
Кроме замечаний нужно исправить ошибки линтера.

2021-07-19 00:14 UTC, AlexMasterov requested changes

2021-07-19 00:14 UTC, AlexMasterov commented on js/utils.js
> +
`mocks.js`
`random.js`

Б12

2021-07-21 02:57 UTC, AlexMasterov requested changes

2021-07-21 02:57 UTC, AlexMasterov commented on js/effects.js
> +  if (currentEffect === 'none') {
<details>
<summary>Проблем</summary>

![image](https://user-images.githubusercontent.com/700213/126422701-3bd3ceef-931e-45a5-a5fa-5affbabe26a3.png)

</details>

```diff
- if (currentEffect === 'none') {
+ if (currentEffect.name === 'none') {
```

2021-07-21 02:57 UTC, AlexMasterov commented on js/filter.js
> +    onFilterChange(target.id.slice(7));
`7`

~Д19

2021-07-21 02:57 UTC, AlexMasterov commented on js/main.js
> +// main.js
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/14b616a9ced52712e9729c298d8766e2344500e5/js/main.js#L13-L29
</details>

Б12

2021-07-21 02:57 UTC, AlexMasterov commented on js/main.js
> +showFilters();
См. 5.2:
> **Блок, с помощью которого производится фильтрация фотографий**, скрыт изначально и **показывается только после окончания загрузки всех фотографий**

Нужно показывать блок с фильтрами после успешной загрузки данных с сервера.

2021-07-21 02:57 UTC, AlexMasterov commented on js/main.js
> +  setFilterChangeHandler((filterName) => {
См. 5.3:
> При переключении фильтров, отрисовка изображений, подходящих под новый фильтр, должна производиться не чаще, чем один раз `500` мс (устранение дребезга)

Нужно доработать.

2021-07-21 02:57 UTC, AlexMasterov commented on js/effects.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/126422827-58fb7aa9-719d-4a86-aad4-ca9032888c41.png)
![image](https://user-images.githubusercontent.com/700213/126422937-56258287-33fd-4100-87b4-a1728277f2a6.png)

</details>

После успешной отправки фото остается её обработчик на `document` для `keydown`.

> Если закрыть сообщение по клику, то он не снимается

Б26

2021-07-21 02:57 UTC, AlexMasterov commented on js/form-validation.js
> +    hashTags.forEach((hashTag) => {
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/126423036-a820c970-253e-496e-af30-15ba0e0e4344.png)

</details>

Если указать теги: `# #tag1 #tag2`, то не появляется сообщение об ошибке.

Б1

См. ТЗ 2.3

2021-07-21 16:26 UTC, EvgenKalinin commented on js/main.js
> +  setFilterChangeHandler((filterName) => {
Не могу. получить обновления от кекса пока не закрыл 11 раздел

2021-07-21 16:50 UTC, merged