Отрисовыввет элементы по мокам
htmlacademy-javascript/414933-kekstagram-23 pull request #6
Opened 2021-06-16 20:04 UTC by EvgenKalinin

2021-06-16 22:46 UTC, AlexMasterov requested changes

2021-06-16 22:46 UTC, AlexMasterov commented on js/miniatures.js
> +    .querySelector('.picture');
<details>
<summary>miniatures.js</summary>

https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/1b5b7bd14a63bb9f77ad0c0b512ced1565de9ad5/js/miniatures.js#L6-L9
</details>

[`Д 21`](https://up.htmlacademy.ru/javascript/23/criteries#d21)
> Поиск элементов по селекторам делается минимальное количество раз, после этого ссылки на элементы сохраняются

Нужно найти элементы _один_ раз, сохранить в переменную за пределами функций, и только переиспользовать.

2021-06-16 22:46 UTC, AlexMasterov commented on js/miniatures.js
> +    const photoElement = userPhotoTemplate.cloneNode(true);
photo`Element`

[`Д 6`](https://up.htmlacademy.ru/javascript/23/criteries#d6)
> Используется единый стиль именования переменных

> если переменные, которые хранят [DOM-элемент](https://developer.mozilla.org/ru/docs/Web/API/Element), содержат слово `Element` или любое другое, **но одно и то же везде**

С _таком_ формулировкой критерия советую вообще не использовать `Element` 😄

2021-06-16 22:46 UTC, AlexMasterov commented on js/random.js
> +const getRandomArrayElement = (elements) => elements[getRandomInt(0, elements.length-1)];
```diff
- const getRandomArrayElement = (elements) => elements[getRandomInt(0, elements.length-1)];
+ const getRandomArrayItem = (items) => items[getRandomInt(0, items.length - 1)];
```

2021-06-16 22:46 UTC, AlexMasterov commented on js/random.js
> +const shuffleArray = (array) => {
`array`

Б5

См. [замечание из прошлого ревью](https://github.com/htmlacademy-javascript/414933-kekstagram-23/pull/4#discussion_r646261938).

2021-06-16 22:46 UTC, AlexMasterov commented on js/random.js
> +  items = shuffleArray(items);
<details>
<summary>shuffleArray</summary>

https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/1b5b7bd14a63bb9f77ad0c0b512ced1565de9ad5/js/random.js#L28-L36
</details>

Функция `shuffleArray` изменяется массив напрямую по _ссылке_. (это плохо)

Поэтому достаточно просто вызывать:

```js
shuffleArray(items);
```
<details>
<summary>random.js</summary>

https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/1b5b7bd14a63bb9f77ad0c0b512ced1565de9ad5/js/random.js#L45
</details>

`let` items = [];

Тогда здесь вместо `let` станет возможно использовать `const`.

2021-06-16 22:46 UTC, AlexMasterov commented on js/miniatures.js
> +  const userPhotos = getMocks();
<details>
<summary>addPhotoMiniatures</summary>

https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/1b5b7bd14a63bb9f77ad0c0b512ced1565de9ad5/js/miniatures.js#L5
https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/1b5b7bd14a63bb9f77ad0c0b512ced1565de9ad5/js/miniatures.js#L11
</details>

Лучше массив `userPhotos` передавать в качестве аргумента при вызове функции.

> Функция `getMocks` будет удалена при реализации получения данных с сервера

2021-06-16 22:46 UTC, AlexMasterov commented on js/miniatures.js
> +const addPhotoMiniatures = (getMocks) => {
<details>
<summary>miniatures.js</summary>

https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/1b5b7bd14a63bb9f77ad0c0b512ced1565de9ad5/js/miniatures.js#L1-L5
https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/1b5b7bd14a63bb9f77ad0c0b512ced1565de9ad5/js/miniatures.js#L11
</details>

> Отрисовывет елементы по данным из **моков**

> getMocks - функция создающая **моки**

Называть подобное моками — большая ошибка, которая может привести к провалу на собеседовании и вызвать непонимание опытных коллег. Такая ошибка невыгодно обнажает отсутствие опыта в _тестировании_ и знаний из умных книжек 😃

Советую разобраться, что в _тестировании_ называют моками, или просто не использовать эту терминологию.

2021-06-17 17:42 UTC, EvgenKalinin commented on js/miniatures.js
> +    .querySelector('.picture');
Я правильно понял, что ошибка в том что поиск происходит внутри функции или что то упустил?

2021-06-17 18:00 UTC, AlexMasterov commented on js/miniatures.js
> +    .querySelector('.picture');
> Я правильно понял, что ошибка в том что поиск происходит внутри функции или что то упустил?

Да, но это не ошибка, а нарушение критерия.

По ТЗ создавать и перерисововать миниатюры потребуется часто, поиск их элементов в DOM будет повторяется с каждым вызовом функции.

2021-06-17 18:52 UTC, AlexMasterov commented
👍🏻

2021-06-17 18:52 UTC, merged