Module7 task2
htmlacademy-javascript/414933-kekstagram-23 pull request #7
Opened 2021-06-22 17:37 UTC by EvgenKalinin

2021-06-23 05:41 UTC, AlexMasterov requested changes

2021-06-23 05:41 UTC, AlexMasterov commented on js/big-photo-overlay.js
> +        newComment.innerHTML = `<img class="social__picture" src="${  comment.avatar  }" alt="${  comment.name }" width="35" height="35"> <p class="social__text">${  comment.comment  }</p>`;
newComment.`innerHTML` = `${  comment.avatar  }` `${  comment.name }` `${  comment.comment  }`

Открытая уязвимость для [XSS-атаки](https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D0%B6%D1%81%D0%B0%D0%B9%D1%82%D0%BE%D0%B2%D1%8B%D0%B9_%D1%81%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%B8%D0%BD%D0%B3).

[`Б 27`](https://up.htmlacademy.ru/javascript/23/criteries#b27)
> Для вставки пользовательских строк (имён, фамилий и так далее) использован `textContent`

2021-06-23 05:41 UTC, AlexMasterov commented on js/big-photo-overlay.js
> +    picture.addEventListener('click', () => {
<details>
<summary>big-photo-overlay.js</summary>

https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/0d079540cc1201d1b0634885b5b6dd1f1e520ed1/js/big-photo-overlay.js#L31-L33
https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/0d079540cc1201d1b0634885b5b6dd1f1e520ed1/js/big-photo-overlay.js#L36
</details>

**4x** `userPictures[i]`

Получение одного и того же элемента из массива по индексу повторяется много раз, что неэффективно.

2021-06-23 05:41 UTC, AlexMasterov commented on js/big-photo-overlay.js
> +  .querySelector('img');
bigPictureOverlay.`querySelector`('.big-picture__img').`querySelector`('img')

Два запроса можно объединить в один.

См. [справку о селекторах](https://developer.mozilla.org/ru/docs/Learn/CSS/Building_blocks/Selectors#%D1%81%D0%BF%D1%80%D0%B0%D0%B2%D0%BA%D0%B0_%D0%BE_%D1%81%D0%B5%D0%BB%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B0%D1%85).

2021-06-23 05:41 UTC, AlexMasterov commented on js/big-photo-overlay.js
> +      document.addEventListener('keydown', (evt) => {
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/123039861-7fd74b00-d3fb-11eb-9926-7492036ccc92.png)

</details>

При открытии фотографии в полноразмерном режиме на `document` накапливаются обработчики `keydown`, что нарушает логику закрытия и ведет к [утечке памяти](https://ru.wikipedia.org/wiki/%D0%A3%D1%82%D0%B5%D1%87%D0%BA%D0%B0_%D0%BF%D0%B0%D0%BC%D1%8F%D1%82%D0%B8).

[`Б 26`](https://up.htmlacademy.ru/javascript/23/criteries#b26)
> Обработчики событий добавляются и удаляются своевременно

2021-06-23 05:41 UTC, AlexMasterov commented on js/big-photo-overlay.js
> +        if ((isEscEvent(evt))) {
if (`(`isEscEvent(evt)`)`) {

Кавычки `()` избыточны.

2021-06-23 05:41 UTC, AlexMasterov commented on js/big-photo-overlay.js
> +      document.addEventListener('keydown', (evt) => {
См. задание:
> Напишите код для закрытия окна по нажатию клавиши `Esc` и клике по иконке закрытия

Если открыть больше одной фотографии в полноразмерном режиме, то перестает работать закрытие по `Esc`.

Нужно разобраться и исправить.

2021-06-23 05:41 UTC, AlexMasterov commented on js/big-photo-overlay.js
> +      bigPictureOverlay.classList.remove('hidden');
<details>
<summary>big-photo-overlay.js</summary>

https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/0d079540cc1201d1b0634885b5b6dd1f1e520ed1/js/big-photo-overlay.js#L30
</details>

В этом месте элемент становится видимым в DOM и тем самым **включается в рендер браузера**.

<details>
<summary>big-photo-overlay.js</summary>

https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/0d079540cc1201d1b0634885b5b6dd1f1e520ed1/js/big-photo-overlay.js#L31-L34
https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/0d079540cc1201d1b0634885b5b6dd1f1e520ed1/js/big-photo-overlay.js#L46
</details>

Далее изменения уже видимого элемента приводят к избыточным перерисовкам страницы.

[`Б 25`](https://up.htmlacademy.ru/javascript/23/criteries#b25)
> Множественные DOM-операции производятся на элементах, которые не добавлены в DOM

2021-06-23 05:41 UTC, AlexMasterov commented on js/big-photo-overlay.js
> +        closeOverlay(evt);
<details>
<summary>big-photo-overlay.js</summary>

https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/0d079540cc1201d1b0634885b5b6dd1f1e520ed1/js/big-photo-overlay.js#L15-L19
</details>

Из-за параметра `evt` для вызова `evt.preventDefault()` функцию  `closeOverlay` нельзя переиспользовать вне события.

2021-06-23 05:41 UTC, AlexMasterov commented on js/big-photo-overlay.js
> +      overlayCloseButton.addEventListener('click', (evt) => {
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/123041765-74d1ea00-d3fe-11eb-97aa-07c167857600.png)

</details>

При открытии одной фотографии в полноразмерном режиме на `overlayCloseButton` накапливаются обработчики `click`.

[`Б 26`](https://up.htmlacademy.ru/javascript/23/criteries#b26)
> Обработчики событий добавляются и удаляются своевременно

2021-06-23 05:46 UTC, AlexMasterov commented on js/big-photo-overlay.js
> +    picture.addEventListener('click', () => {
<details>
<summary>big-photo-overlay.js</summary>

https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/0d079540cc1201d1b0634885b5b6dd1f1e520ed1/js/big-photo-overlay.js#L26-L29
</details>

🤔

Элемент каждой `.picture` доступен еще при [создании миниатюры](https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/0d079540cc1201d1b0634885b5b6dd1f1e520ed1/js/miniatures.js#L14).

2021-06-23 06:46 UTC, AlexMasterov commented on js/utils.js
> +const isEscEvent = (evt) => evt.key === 'Escape' || evt.key === 'Esc';
evt.key === `'Escape'` || evt.key === `'Esc'`

Б7

Могут придраться на защите проекта.

<details>
<summary>Покажи, что можно сделать</summary>

В последних версиях V8 [Array.p.`includes`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) будет работать почти также быстро, как два простых сравнения:
```js
const KEYBOARD_KEYS = [
  'Escape',
  'Esc',
];

const isEscEvent = (evt) => KEYBOARD_KEYS.includes(evt.key);
```
</details>

2021-06-23 06:52 UTC, AlexMasterov commented on js/big-photo-overlay.js
> +  pageBody.classList.remove('modal-open');
Если `bigPictureOverlay` отобразиться с большим количеством комментариев, то по умолчанию будет отрисован (и вычислен) доп. скролл.

Лучше сначала убрать доп. скролл, а только потом отобразить `bigPictureOverlay`.

2021-06-23 07:01 UTC, AlexMasterov commented on js/big-photo-overlay.js
> +      pageBody.classList.add('modal-open');
Если `bigPictureOverlay` отобразиться с большим количеством комментариев, то по умолчанию будет отрисован (и вычислен) доп. скролл.

Лучше сначала убрать доп. скролл, а только потом отобразить `bigPictureOverlay`.

2021-06-23 22:26 UTC, EvgenKalinin commented on js/big-photo-overlay.js
> +      document.addEventListener('keydown', (evt) => {
Не понял ошибку

2021-06-23 22:26 UTC, EvgenKalinin commented on js/big-photo-overlay.js
> +      bigPictureOverlay.classList.remove('hidden');
Не понял ошибку((

2021-06-23 22:26 UTC, EvgenKalinin commented on js/big-photo-overlay.js
> +        closeOverlay(evt);
тут вроде поправил

2021-06-23 22:26 UTC, EvgenKalinin commented on js/big-photo-overlay.js
> +    picture.addEventListener('click', () => {
Не понял замечание

2021-06-24 09:04 UTC, AlexMasterov commented on js/big-photo-overlay.js
> +    picture.addEventListener('click', () => {
<details>
<summary>miniatures.js</summary>

https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/1cd5cf226a8d9b564a092d2fa551221518b08c18/js/miniatures.js#L10-L22
</details>

Посмотри внимательно, при создании миниатюр одновременно доступны данные фото и элементы, что позволяет сразу добавить обработчик на `click` и (через замыкание) использовать данные для фотографии в полноразмерном режиме.

Вместо этого ты сначала добавляешь DOM-элементы миниатюр в DOM (браузер), а в другом модуле обращаешься за ними, чтобы добавить обработчик на `click`. При этом, добавление обработчиков происходит на основе совпадения порядка данных фото в массиве (JS) с порядком DOM-элементов в коллекции (браузер) 🤔

2021-06-24 09:08 UTC, AlexMasterov commented on js/big-photo-overlay.js
> +        closeOverlay(evt);
<details>
<summary>big-photo-overlay.js</summary>

https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/1cd5cf226a8d9b564a092d2fa551221518b08c18/js/big-photo-overlay.js#L16-L17
https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/1cd5cf226a8d9b564a092d2fa551221518b08c18/js/big-photo-overlay.js#L23-L24
</details>

Теперь исходная проблема проявилась в дублирование, что проще для замечания, а его учет окончательно доведет до ожидаемого решения 😃

[`Д 14`](https://up.htmlacademy.ru/javascript/23/criteries#d14)
> Отсутствует дублирование кода: **повторяющиеся части кода переписаны как _функции_**

2021-06-24 09:16 UTC, AlexMasterov commented on js/big-photo-overlay.js
> +      document.addEventListener('keydown', (evt) => {
> Не понял ошибку

Проверял на коммите https://github.com/htmlacademy-javascript/414933-kekstagram-23/pull/7/commits/0d079540cc1201d1b0634885b5b6dd1f1e520ed1.

Если несколько раз открыть миниатюру в полноразмерном режиме и закрыть по `Esc`, то закрытие по `Esc` перестанет работать, в том числе для остальных фотографий.

> Проблема связана с накоплением обработчиков на `document`, см. [соответствующие замечание](https://github.com/htmlacademy-javascript/414933-kekstagram-23/pull/7#discussion_r656766213)

2021-06-24 09:21 UTC, AlexMasterov commented on js/big-photo-overlay.js
> +      bigPictureOverlay.classList.remove('hidden');
> Не понял ошибку((

Набери в любой искалке: `What forces layout / reflow`.

Думаю, что на текущем уровне для критерия будет достаточно использования фрагмента для комментариев.

2021-06-24 09:30 UTC, AlexMasterov commented on js/big-photo-overlay.js
> +const showPreviewOverlay = (userPictures) => {
<details>
<summary>showPreviewOverlay</summary>

https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/1cd5cf226a8d9b564a092d2fa551221518b08c18/js/big-photo-overlay.js#L32-L79
</details>

Эта большая функция называется `showPreviewOverlay`, но на самом деле лишь добавляет обработчики на `click`.

[`Б 6`](https://up.htmlacademy.ru/javascript/23/criteries#b6)
> **Название функции  должно** быть глаголом и **соответствовать действию**, которое выполняет функция

2021-06-24 20:26 UTC, AlexMasterov requested changes
К сожалению, нужно еще немного доработать.

2021-06-24 20:26 UTC, AlexMasterov commented on js/big-photo-overlay.js
> +      document.addEventListener('keydown', onOverlayEscKeydown);
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/123325413-a94dbf00-d540-11eb-944b-580bee0fdc9c.png)

</details>

После закрытия окна с фотографией на `document` остается обработчик `keydown`.

[`Б 26`](https://up.htmlacademy.ru/javascript/23/criteries#b26)
> Обработчики событий добавляются и удаляются своевременно

> Например, на странице может существовать попап, который скрывается по `ESC`. Лучше для него гасить обработчик, если он не показан, потому что он может каким-то образом ломать поведение сайта — останавливать распространение, отменять поведение по умолчанию и так далее. Поэтому поведение должно быть явным — **если в этот момент времени обработчики не нужны, их нужно удалить**

Нужно разобраться и исправить.

2021-06-24 20:26 UTC, AlexMasterov commented on js/big-photo-overlay.js
> +    document.removeEventListener('keydown', onOverlayEscKeydown);
<details>
<summary>big-photo-overlay.js</summary>

https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/ee1745447dd19faef31b3772159d8ac956fc53a8/js/big-photo-overlay.js#L38-L83
</details>

```js
pictures.forEach((picture, i) => {
  picture.addEventListener('click', () => {
    overlayCloseButton.addEventListener('click', onOverlayCloseButtonClick);
    document.addEventListener('keydown', onOverlayEscKeydown);
  });

  // Удаляем обработчики
  overlayCloseButton.removeEventListener('click', onOverlayCloseButtonClick);
  document.removeEventListener('keydown', onOverlayEscKeydown);
});
```
Функция `showPreviewOverlay`, не смотря на название, только добавляет обработчики на `click` по миниатюре. Обработчики для `overlayCloseButton` (`click`) и `document` (`keydown`) будут добавлены только при клике на миниатюру.

Поэтому при первом вызове `showPreviewOverlay` (и без клика по миниатюре) обработчиков еще нет и удалять соответственно нечего. Повторный вызов `showPreviewOverlay` [приведет лишь к накоплению обработчиков](https://github.com/htmlacademy-javascript/414933-kekstagram-23/pull/7#discussion_r657766489).

Обработчиков нет, но их пытаются удалить на _каждой_ итерации цикла, что неправильно и бессмысленно.

2021-06-24 20:26 UTC, AlexMasterov commented on js/big-photo-overlay.js
> +        const newCommentP = newComment.children[1];
Можно сократить:
```js
const [newCommentImg, newCommentP] = newComment.children;
```
Но важно знать, если в разметке изменится порядок CSS-классов, то в обоих случаях _такой_ код перестанет работать.

2021-06-24 20:26 UTC, AlexMasterov commented on js/big-photo-overlay.js
> +        // newComment.innerHTML = `<img class="social__picture" src="${  comment.avatar  }" alt="${  comment.name }" width="35" height="35"> <p class="social__text">${  comment.comment  }</p>`;
`//`

[`Б 12`](https://up.htmlacademy.ru/javascript/23/criteries#b12)
> В коде проекта нет файлов, модулей и частей кода, которые не используются, в**ключая закомментированные участки кода**

2021-06-24 20:26 UTC, AlexMasterov commented on js/big-photo-overlay.js
> +    closeOverlay();
👍🏻

2021-06-24 21:42 UTC, AlexMasterov commented
👍🏻

2021-06-24 21:42 UTC, merged