Module8 task2
htmlacademy-javascript/414933-kekstagram-23 pull request #9
Opened 2021-07-02 20:36 UTC by EvgenKalinin

2021-07-02 21:03 UTC, AlexMasterov requested changes

2021-07-02 21:39 UTC, AlexMasterov requested changes

2021-07-02 21:39 UTC, AlexMasterov commented on js/big-photo-overlay.js
Если открыть фотографию и по кнопке "Загрузить еще" отобразить следующие или все доступные комментарии, то при повторном открытии счетчик не сбрасывается.

См. 4.6:
> Сразу после открытия изображения в полноэкранном режиме отображается не более `5` комментариев

Нужно доработать.

2021-07-02 21:44 UTC, AlexMasterov commented on js/big-photo-overlay.js
> +        evt.preventDefault;
evt.`preventDefault`;

Метод без вызова.

2021-07-02 21:46 UTC, AlexMasterov requested changes

2021-07-02 21:46 UTC, AlexMasterov commented on js/big-photo-overlay.js
> +        for (let j = 0; j < commentsToShow && j < commentItems.length; j++) {
for (let `j` = 0; `j` < commentsToShow && `j` < commentItems.length; `j`++) {

Б4

2021-07-02 21:50 UTC, AlexMasterov commented on js/big-photo-overlay.js
> +        commentItems[j].style.display = 'flex';
<details>
<summary>big-photo-overlay.js</summary>

https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/278e322325913dd86d562f1a536d3377ed91a332/js/big-photo-overlay.js#L84-L87
https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/278e322325913dd86d562f1a536d3377ed91a332/js/big-photo-overlay.js#L89-L91
</details>

Б25, Д23

2021-07-03 16:09 UTC, EvgenKalinin commented on js/big-photo-overlay.js
> +        for (let j = 0; j < commentsToShow && j < commentItems.length; j++) {
Если поменять все `j` на `i` пишет что и уже  объявлено в верхней области видимости.
Если менять без объявления, то все ломается и в оверлэй передается другая картинка

2021-07-03 16:15 UTC, EvgenKalinin commented on js/big-photo-overlay.js
Саш, я тут застрял(( 
Счетчик вроде сбрасывается. 
Но появилась проблема. Если нажать на "Загрузить еще"(допустим 1 раз) - появится 5 новых комментов(общее кол-во 10), затем закрыть окно, снова открыть и нажать "Загрузить еще" то сразу откроется 10комментов(общее кол-во станет 15). Не пойму что не так.

2021-07-04 00:35 UTC, AlexMasterov commented on js/big-photo-overlay.js
В твоем решении в карточку, которая уже находится в DOM (браузер), добавляются сразу все элементы комментариев. После этого находишь эти же элементы комментариев в DOM и в цикле изменяешь их видимость `.display` на `none` (хотя в другом месте используешь класс `hidden`). Далее еще в одном цикле первым 5-и меняешь `.display` на `flex`.

Вместо скрытия и показа всех элементов лучше добавлять их по необходимости, когда пользователь нажимает кнопку "Загрузить еще".

2021-07-04 00:35 UTC, AlexMasterov commented on js/big-photo-overlay.js
> Если нажать на "Загрузить еще"(допустим 1 раз) - появится 5 новых комментов(общее кол-во 10), затем закрыть окно, снова открыть и нажать "Загрузить еще" то сразу откроется 10комментов(общее кол-во станет 15). Не пойму что не так

<details>
<summary>big-photo-overlay.js</summary>

https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/03e89902f233228b6f7e5a4dbce4499920daa223/js/big-photo-overlay.js#L95-L97
</details>

<details>
<summary>onCommentLoaderClick </summary>

https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/03e89902f233228b6f7e5a4dbce4499920daa223/js/big-photo-overlay.js#L112
</details>

Ты доработал сброс счетчика, но у показанных 5+N элементов остается `.display = flex` (вместо `none`).

В твоем решение для "сброса" нужно снова скрыть все элементы комментариев, кроме первых 5-и.

2021-07-04 00:39 UTC, AlexMasterov requested changes

2021-07-04 00:39 UTC, AlexMasterov commented on js/big-photo-overlay.js
> +  commentsToShow = 5;
<details>
<summary>big-photo-overlay.js</summary>

https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/03e89902f233228b6f7e5a4dbce4499920daa223/js/big-photo-overlay.js#L4
https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/03e89902f233228b6f7e5a4dbce4499920daa223/js/big-photo-overlay.js#L20
</details>

`5`

Б7

Для обоих случаев используй значение `5` из константы:

https://github.com/htmlacademy-javascript/414933-kekstagram-23/blob/03e89902f233228b6f7e5a4dbce4499920daa223/js/big-photo-overlay.js#L3

2021-07-10 14:18 UTC, merged